#!/bin/bash
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON\
   -DLLVM_ENABLE_ASSERTIONS=ON\
   -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra"\
   -DCMAKE_BUILD_TYPE="RelWithDebInfo"\
   -DBUILD_SHARED_LIBS=ON\
   -DLLVM_PARALLEL_LINK_JOBS=2\
   -DLLVM_BUILD_EXAMPLES=ON\
   -DLLVM_INCLUDE_EXAMPLES=ON\
   -DLLVM_TARGETS_TO_BUILD="NVPTX;X86"\
   ../llvm
